// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";
import { SuspenseWrapper } from "./utils/suspense";



const App = lazy(() => import("./pages/App.tsx"));
const CharacterCreationPage = lazy(() => import("./pages/CharacterCreationPage.tsx"));
const GamePage = lazy(() => import("./pages/GamePage.tsx"));
const LoginPage = lazy(() => import("./pages/LoginPage.tsx"));
const SignUpPage = lazy(() => import("./pages/SignUpPage.tsx"));
const ShopPage = lazy(() => import("./pages/ShopPage.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <SuspenseWrapper><App /></SuspenseWrapper>},
	{ path: "/character-creation-page", element: <SuspenseWrapper><CharacterCreationPage /></SuspenseWrapper>},
	{ path: "/charactercreationpage", element: <SuspenseWrapper><CharacterCreationPage /></SuspenseWrapper>},
	{ path: "/game-page", element: <SuspenseWrapper><GamePage /></SuspenseWrapper>},
	{ path: "/gamepage", element: <SuspenseWrapper><GamePage /></SuspenseWrapper>},
	{ path: "/login-page", element: <SuspenseWrapper><LoginPage /></SuspenseWrapper>},
	{ path: "/loginpage", element: <SuspenseWrapper><LoginPage /></SuspenseWrapper>},
	{ path: "/login", element: <SuspenseWrapper><LoginPage /></SuspenseWrapper>},
	{ path: "/sign-up-page", element: <SuspenseWrapper><SignUpPage /></SuspenseWrapper>},
	{ path: "/signuppage", element: <SuspenseWrapper><SignUpPage /></SuspenseWrapper>},
	{ path: "/sign-up", element: <SuspenseWrapper><SignUpPage /></SuspenseWrapper>},
	{ path: "/shop", element: <SuspenseWrapper><ShopPage /></SuspenseWrapper>},

];
