// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const App = lazy(() => import("./pages/App.tsx"));
const CharacterCreationPage = lazy(() => import("./pages/CharacterCreationPage.tsx"));
const GamePage = lazy(() => import("./pages/GamePage.tsx"));
const LoginPage = lazy(() => import("./pages/LoginPage.tsx"));
const SignUpPage = lazy(() => import("./pages/SignUpPage.tsx"));
const ShopPage = lazy(() => import("./pages/ShopPage.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/character-creation-page", element: <CharacterCreationPage />},
	{ path: "/charactercreationpage", element: <CharacterCreationPage />},
	{ path: "/game-page", element: <GamePage />},
	{ path: "/gamepage", element: <GamePage />},
	{ path: "/login-page", element: <LoginPage />},
	{ path: "/loginpage", element: <LoginPage />},
	{ path: "/sign-up-page", element: <SignUpPage />},
	{ path: "/signuppage", element: <SignUpPage />},
	{ path: "/shop", element: <ShopPage />},

];
